export type FieldType =
    | 'autocomplete'      // AutoCompleteModule
    | 'cascade-select'    // CascadeSelectModule
    | 'checkbox'          // CheckboxModule
    | 'colorpicker'       // ColorPickerModule
    | 'datepicker'        // DatePickerModule
    | 'editor'            // EditorModule
    | 'float-label'       // FloatLabelModule
    | 'icon-field'        // IconFieldModule
    | 'input-icon'        // InputIconModule
    | 'ifta-label'        // IftaLabelModule
    | 'input-group'       // InputGroupModule
    | 'input-group-addon' // InputGroupAddonModule
    | 'input-mask'        // InputMaskModule
    | 'input-number'      // InputNumberModule
    | 'input-otp'         // InputOtpModule
    | 'input-text'        // InputTextModule
    | 'key-filter'        // KeyFilterModule
    | 'knob'              // KnobModule
    | 'listbox'           // ListboxModule
    | 'multi-select'      // MultiSelectModule
    | 'password'          // PasswordModule
    | 'radio'             // RadioButtonModule
    | 'rating'            // RatingModule
    | 'select'            // SelectModule
    | 'select-button'     // SelectButtonModule
    | 'slider'            // SliderModule
    | 'textarea'          // TextareaModule
    | 'toggle-button'     // ToggleButtonModule
    | 'toggle-switch'     // ToggleSwitchModule
    | 'tree-select'       // TreeSelectModule
    | 'imagefield';       // Custom Image Field (FormArray of filenames)
