import { FieldConfig } from '../../../core/models/interfaces/legacy-extras';

export const nativeTools: FieldConfig[] = [
  {
    id: 'native-text-1',
    formControl: 'native_text',
    kind: 'control',
    key: 'native_text',
    type: 'input-text',
    label: 'Text Input',
    fieldStyle: { width: '100%' },
    options: [],
  },
  {
    id: 'native-password-1',
    formControl: 'native_password',
    kind: 'control',
    key: 'native_password',
    type: 'password',
    label: 'Password',
    fieldStyle: { width: '100%' },
    options: [],
  },
  {
    id: 'native-email-1',
    formControl: 'native_email',
    kind: 'control',
    key: 'native_email',
    type: 'input-text',
    label: 'Email',
    fieldStyle: { width: '100%' },
    inputAttrs: { type: 'email' },
    options: [],
  },
  {
    id: 'native-number-1',
    formControl: 'native_number',
    kind: 'control',
    key: 'native_number',
    type: 'input-number',
    label: 'Number',
    fieldStyle: { width: '100%' },
    options: [],
  },
  {
    id: 'native-date-1',
    formControl: 'native_date',
    kind: 'control',
    key: 'native_date',
    type: 'datepicker',
    label: 'Date',
    fieldStyle: { width: '100%' },
    options: [],
  },
  {
    id: 'native-textarea-1',
    formControl: 'native_textarea',
    kind: 'control',
    key: 'native_textarea',
    type: 'textarea',
    label: 'Textarea',
    fieldStyle: { width: '100%' },
    options: [],
  },
  {
    id: 'native-select-1',
    formControl: 'native_select',
    kind: 'control',
    key: 'native_select',
    type: 'select',
    label: 'Select',
    fieldStyle: { width: '100%' },
    options: [
      { label: 'Option 1', value: 'option1' },
      { label: 'Option 2', value: 'option2' },
    ],
  },
  {
    id: 'native-multi-select-1',
    formControl: 'native_multi_select',
    kind: 'control',
    key: 'native_multi_select',
    type: 'multi-select',
    label: 'Multi Select',
    fieldStyle: { width: '100%' },
    options: [
      { label: 'Option 1', value: 'option1' },
      { label: 'Option 2', value: 'option2' },
    ],
  },
  {
    id: 'native-radio-1',
    formControl: 'native_radio',
    kind: 'control',
    key: 'native_radio',
    type: 'radio',
    label: 'Radio',
    fieldStyle: { width: '100%' },
    options: [
      { label: 'Option 1', value: 'option1' },
      { label: 'Option 2', value: 'option2' },
    ],
  },
  {
    id: 'native-checkbox-1',
    formControl: 'native_checkbox',
    kind: 'control',
    key: 'native_checkbox',
    type: 'checkbox',
    label: 'Checkbox',
    fieldStyle: { width: '100%' },
    options: [],
  },
  {
    id: 'native-attachment-1',
    formControl: 'native_attachment',
    kind: 'control',
    key: 'native_attachment',
    type: 'attachment',
    label: 'Attachment',
    fieldStyle: { width: '100%' },
    componentProps: {
      description: 'Upload files',
      uploadUrl: '/api/upload',
    },
    options: [],
  },
  {
    id: 'native-submit-1',
    formControl: 'native_submit',
    kind: 'control',
    key: 'native_submit',
    type: 'submit' as any,
    label: 'Submit',
    action: 'submit',
    fieldStyle: {
      backgroundColor: '#22c55e',
      padding: '0.5rem 1rem',
      borderRadius: '2rem',
      width: '100%',
    },
    styles: {
      color: '#ffffff',
      cursor: 'pointer',
      transition: 'all 0.3s ease-in-out',
    },
    options: [],
  },
  {
    id: 'native-array-1',
    kind: 'array',
    key: 'native_array',
    type: 'array' as any,
    label: 'Array',
    fieldStyle: { columns: 4, width: '100%' },
    children: [],
  },
];
